### ISSUE TITLE
example to train

### ISSUE THREAD

**Issue by deyituo** [PlayVoice/Uni-SVC#13]
Could you provide a example to train a voice?

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/VI-SVC/tree/main/svc

**Comment by deyituo** [comment]
em..I see the scripts, but I think that showing a real experiment from prepare dataset to showing outputs would be better, or no body knows how good this project is.

**Comment by MaxMax2016** [comment]
ok, i will do this, but after some days latter. because of another project.

**Comment by MaxMax2016** [comment]
@deyituo work flow for opencpop has release

**Comment by diiogofernands** [comment]
Hi @ MaxMax2016, can you provide the scripts for the dataset prepare to SVC model?

**Comment by MaxMax2016** [comment]
@diiogofernands python svc_preprocess_ppg.py -w ./data_opencpop/waves -p ./data_opencpop/whisper

python svc_preprocess_f0.py

python svc_trainer.py -c config/default_c32.yaml -n uni_svc

**Comment by diiogofernands** [comment]
Dear @MaxMax2016, I'm talking about the VI-SVC model, which I'm having some problems with the shape of wave data. And you left the VI-SVC?

**Comment by MaxMax2016** [comment]
different whisper model has different out dim, which you use?

**Comment by diiogofernands** [comment]
I'm using the [base model](https://github.com/PlayVoice/whisper_ppg/blob/main/whisper_ppg_path.py#L45), but I believe that this is not the problem because some samples don't have any issues, as you can see in the log.

`INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[1, 0.0001]
INFO:singing_base:loss_disc=6.023, loss_gen=6.023, loss_fm=0.320
INFO:singing_base:loss_mel=41.158, loss_kl=5.000
path ./data/waves/spk140/MMDB140-36.wav
path ./data/waves/spk075/MMDB075-8.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[2, 0.0001]
INFO:singing_base:loss_disc=6.022, loss_gen=5.221, loss_fm=0.488
INFO:singing_base:loss_mel=41.548, loss_kl=5.000
path ./data/waves/spk038/MMDB038-10.wav
path ./data/waves/spk134/MMDB134-38.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[3, 0.0001]
INFO:singing_base:loss_disc=5.248, loss_gen=4.406, loss_fm=0.281
INFO:singing_base:loss_mel=45.697, loss_kl=5.000
path ./data/waves/spk086/MMDB086-31.wav
path ./data/waves/spk146/MMDB146-52.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[4, 0.0001]
INFO:singing_base:loss_disc=4.533, loss_gen=3.463, loss_fm=0.319
INFO:singing_base:loss_mel=47.529, loss_kl=5.000
path ./data/waves/spk056/MMDB056-11.wav
path ./data/waves/spk072/MMDB072-5.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[5, 0.0001]
INFO:singing_base:loss_disc=3.822, loss_gen=2.392, loss_fm=0.361
INFO:singing_base:loss_mel=43.210, loss_kl=5.000
path ./data/waves/spk008/MMDB008-37.wav
path ./data/waves/spk131/MMDB131-29.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[6, 0.0001]
INFO:singing_base:loss_disc=3.258, loss_gen=1.368, loss_fm=0.397
INFO:singing_base:loss_mel=45.283, loss_kl=5.000
path ./data/waves/spk036/MMDB036-27.wav
path ./data/waves/spk120/MMDB120-57.wav
INFO:singing_base:Train Epoch: 1 [0%]
INFO:singing_base:[7, 0.0001]
INFO:singing_base:loss_disc=3.165, loss_gen=0.877, loss_fm=0.508
INFO:singing_base:loss_mel=34.761, loss_kl=5.000
path ./data/waves/spk148/MMDB148-1.wav
path ./data/waves/spk149/MMDB149-42.wav
Traceback (most recent call last):
  File "train.py", line 440, in <module>
    main()
  File "train.py", line 40, in main
    mp.spawn(
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/workspace/ceia_projects/moises/VI-SVC/svc/train.py", line 144, in run
    train_and_evaluate(
  File "/home/workspace/ceia_projects/moises/VI-SVC/svc/train.py", line 221, in train_and_evaluate
    ) = net_g(phone, phone_lengths, pitch, nsff0, spec, spec_lengths, spkid)
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/opt/conda/envs/vits/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/workspace/ceia_projects/moises/VI-SVC/svc/models.py", line 455, in forward
    z_slice, ids_slice = commons.rand_slice_segments(
  File "/home/workspace/ceia_projects/moises/VI-SVC/svc/commons.py", line 59, in rand_slice_segments
    ret = slice_segments(x, ids_str, segment_size)
  File "/home/workspace/ceia_projects/moises/VI-SVC/svc/commons.py", line 49, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (64) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [192, 64].  Tensor sizes: [192, 0]`

**Comment by MaxMax2016** [comment]
VI-SVC hasn't finished because of nsf decoder, you can try SO-VITS-SVC, https://github.com/innnky/so-vits-svc , and you can change hubert to whisper. i will recheck the vi-svc after finish UNI-SVC. So sorry！

**Comment by diiogofernands** [comment]
Thanks, for UNI-SVC can you explain more details on the inference stage,  the script uses only a wave input, it's for what target song?

**Comment by MaxMax2016** [comment]
get phone info for wav by whisper audio encoder and get pit for wav，the uni-svc chang the wav‘s timbre to target speaker.
